language: csharp
mono: beta
os: osx
sudo: required

before_install:
  - git submodule update --init --recursive
  - wget https://dl.xamarin.com/XamarinforMac/Mac/xamarin.mac-6.8.3.0.pkg
  - wget https://download.visualstudio.microsoft.com/download/pr/2aa9c320-b801-4fcb-af34-b01feb48f61d/2ff54bbeed83c42a0dc2c9fb9f3cc13a/visualstudioformac-8.4.0.2657.dmg
  - sudo installer -pkg xamarin.mac*.pkg -target /
  - hdiutil attach visualstudioformac-*.dmg
  - cp -R /Volumes/Visual\ Studio/Visual\ Studio.app /Applications/

script:
  - msbuild samples/FigmaSharp/MainSample/MainSample.Cocoa/FigmaSharpApp.csproj /p:"Configuration=Release;Platform=AnyCPU" /restore
  - msbuild FigmaSharp.Tools/MonoDevelop.Figma/MonoDevelop.Figma.csproj /p:Configuration=Release /p:InstallAddin=true /restore

before_deploy:
  - cd ${TRAVIS_BUILD_DIR}/samples/FigmaSharp/MainSample/MainSample.Cocoa/bin/Release
  - zip --recurse-paths FigmaSharpApp-${TRAVIS_COMMIT}.zip FigmaSharpApp.app && mv FigmaSharpApp-${TRAVIS_COMMIT}.zip ${TRAVIS_BUILD_DIR}
  - mv ${TRAVIS_BUILD_DIR}/FigmaSharp.Tools/MonoDevelop.Figma/bin/Release/*/*.mpack ${TRAVIS_BUILD_DIR}/FigmaSharpExtension-${TRAVIS_COMMIT}.mpack

deploy:
  provider: releases
  on:
    repo: hbons/FigmaSharp
  file:
    - ${TRAVIS_BUILD_DIR}/FigmaSharpApp-${TRAVIS_COMMIT}.zip
    - ${TRAVIS_BUILD_DIR}/FigmaSharpExtension-${TRAVIS_COMMIT}.mpack
  prerelease: true
  overwrite: true
  skip_cleanup: true
  api_key:
    secure: Q673xZSt9qqDa1EAJDghkiNU/2vl/lHEtrw6zK0Y9s6eMGetVNubzdjW7MsG4cdbR52fzES1PRf421AT5mGAe29/B51uoaxkkDTdVDcMxL2SM/Lw8N1B6WdfpxBPFHVQhF0L1nGufdu8yIuHoFZy1WrqtNpnrlM0TWRdV1xbt3yRXu1GgPFx+FXNN7GcAuXry+PJmz2CqE5OaxN7j8btQ1s/cQGjW4hLxrM5aGad19Xq97uO/kaWN2XmWD5Bv1AWm8ZsSoxyRB5KJAgj6DfwHLkGWDcbHlAyZsZDSYUgkqjXXfXEkzqOuWX1C+sQTN3KjRCjYiadcbvUsoG9Qg4pO8DSehFnxoprsNOfbyZn7BdP+1v+FCBXAO46l/TcrKsbe8RgdKqb/fSiopg+ZbHRkvXzZ+2wtqPROhRzJ43KtalAl4rnYT8cYScBRmL90QUjnos7DwGDQhWvaFhQJj2YzAYazjccz2gCUnD9IWzLkSa5X2PVN+XYJSdaYitsikl3RxbPmk+Aulp3bizpbX07fEc3NZdcWwGr0wZx8YsLQltzPyKZuOcqHp7EDwDqQzMApv+AYwyF4B9mf3vceNJY+/6vGU8J4eQ7L0Lv7W5LeD0T1YPVM7Tk3lEBmzxVJpain566X1p6J+Wbcv5Fqc+1ht/ssPPcFm87fAnGw55PwL4=
  on:
    repo: netonjm/FigmaSharp

