trigger:
  - main

pool:
  vmImage: 'macOS-10.15'

variables:
  - name: SOURCES_DIRECTORY
    value: $(Build.SourcesDirectory)
  - name: SOURCE_VERSION
    value: $(Build.SourceVersion)

steps:
  - task: Bash@3
    name: 'BuildMacApp'
    inputs:
      targetType: 'inline'
      script: |      
        msbuild tools/FigmaSharpApp/FigmaSharpApp.csproj /p:"Configuration=Release;Platform=AnyCPU" /restore

  - task: Bash@3
    name: 'BuildMacExtension'
    inputs:
      targetType: 'inline'
      script: |      
        msbuild tools/MonoDevelop.Figma/MonoDevelop.Figma.csproj /p:Configuration=Release /p:InstallAddin=true /restore

  - task: Bash@3
    name: 'PreparePublish'
    inputs:
      targetType: 'inline'
      script: |      
        cd ${SOURCES_DIRECTORY}/tools/FigmaSharpApp/bin/Release
        zip --recurse-paths FigmaSharpApp-${SOURCE_VERSION}.zip FigmaSharpApp.app && mv FigmaSharpApp-${SOURCE_VERSION}.zip ${SOURCES_DIRECTORY}
        mv ${SOURCES_DIRECTORY}/tools/MonoDevelop.Figma/bin/Release/*/*.mpack ${SOURCES_DIRECTORY}/FigmaSharpExtension-${SOURCE_VERSION}.mpack

  - task: GitHubRelease@0
    inputs:
      gitHubConnection: 
      repositoryName: '$(Build.Repository.Name)'
      action: 'create'
      target: '$(Build.SourceVersion)'
      addChangeLog: false
      assets: |
        $(Build.SourcesDirectory)/FigmaSharpApp-$(Build.SourceVersion).zip
        $(Build.SourcesDirectory)/FigmaSharpExtension-$(Build.SourceVersion).mpack
