# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macOS-10.15'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      rm -Rf /Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Mac
      wget https://dl.xamarin.com/XamarinforMac/Mac/xamarin.mac-6.8.3.0.pkg
      sudo installer -pkg xamarin.mac*.pkg -target /



      git submodule update --init --recursive
      
      msbuild tools/FigmaSharpApp/FigmaSharpApp.csproj /p:"Configuration=Release;Platform=AnyCPU" /restore
      msbuild tools/MonoDevelop.Figma/MonoDevelop.Figma.csproj /p:Configuration=Release /p:InstallAddin=true /restore





